from pymongo.errors import ConnectionFailure

mongo_uri = "mongodb://127.0.0.1:27017/"  
